name: Hello World

on: 
  workflow_dispatch:
  push:
    branches:
      - 'develop'


jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: echo "Hello World!"
      - run: pwd
      - run: cat hey_develop.txt